@startuml
' Direction hint for a more vertical layout
top to bottom direction

title Original TRIAD: EBT Implementierung

package experiment {

  package enums {
    enum ProjectEnum {
      <b>EBT</b>
      DRONOLOGY
      WARC
      EASYCLINIC
      LIBEST
    }
  }

  package project {
    interface Project
    class EBT implements Project {
      - {static} projectName = "ebt"
      - {static} level1ToLevel2MatricPath = "..."
      - {static} processedLevel1Path = "..."
      ' ... and other hardcoded paths
    }
  }

  ProjectEnum ..> EBT : determines which Project class to instantiate

  package preprocess {
    package ebt {
      class ProcessEBT {
        + {static} main()
        - {static} readCometTxt(...)
        - {static} readCometCodeTxt(...)
      }

      class ExtractEbtMatrices {
        + {static} main()
        - {static} extract(...)
      }
      
      class ExtractCodeElement {
        + {static} main()
        - {static} filterInvokeMethod()
        - {static} readAllMethod()
      }

      class ExtractEbtBiterm {
        - {static} level1BitermsMap
        - {static} level2BitermsMap
        - {static} level3BitermsMap
        + {static} extractBiterms()
      }

      ' Vertical Data Flow
      ProcessEBT --> ExtractEbtBiterm : creates processed .txt files
    }
  }
}


@enduml