@startuml
title Originales TRIAD: Enum Struktur

enum ProjectEnum {
  EBT
  DRONOLOGY
  WARC
  EASYCLINIC
  LIBEST
}

enum ArtifactLevelEnum {
  LEVEL1
  LEVEL2
  LEVEL3
}

enum IREnum {
  VSM
  LSI
  JSD
}

enum CodeEnum {
    CLASS_NAME
    METHOD_NAME
    COMMENT
    INVOKED_METHOD
    FIELD_NAME
    FIELD_TYPE
    PARAM_NAME
    PARAM_TYPE
}

enum LayerEnum {
    TITLE
    MAIN_FLOW
    SUB_FLOW
    ALT_FLOW
    SUMMARY
    DESC
}

note top of ProjectEnum
  Für jeden neuen Datensatz ist
  ein neuer Enum Eintrag nötig.
end note


@enduml